#!/bin/bash
# Regenerate cluster/donors.txt — the SCOPE of the sample catalogue scan — from
# cluster/trees/donor_table.tsv, which is the catalogue of donors we actually have trees for.
#
#   bash cluster/trees/make_donors_txt.sh          # -> cluster/donors.txt
#   bash cluster/trees/make_donors_txt.sh --check  # exit 1 if donors.txt is out of date
#
# WHY THIS EXISTS. donors.txt was maintained by hand and drifted to 97 donors while the tree
# catalogue reached 151. The 34-donor liver cohort and both tonsil donors had ZERO scan
# coverage — so the merged catalogue reported them as "no BAMs found", which reads as an
# absence of data when it was an absence of ASKING. A hand-maintained subset of a generated
# table will always drift; the drift is silent, and it is silent in the direction of
# under-reporting. Generate it instead.
#
# The prose header lives in cluster/donors.header and is NOT generated — edit it there.
# Per-donor clinical detail lives in cluster/trees/donor_clinical.tsv, which this only
# summarises. When they disagree, donor_clinical.tsv wins.
#
# SCOPE IS NOT THE SAME AS USABILITY. Everything with a tree goes in, including donors we
# already know cannot feed a phylogeny (PD60243 is bulk-only; the Fabre donors are targeted
# bulk). Cataloguing a donor is how we CONFIRM that from its BAM headers rather than from a
# note someone wrote. Discovery excludes them; the scan does not.
set -uo pipefail
cd "$(dirname "$0")/../.."

TABLE=cluster/trees/donor_table.tsv
HEADER=cluster/donors.header
DEST=cluster/donors.txt
[ -s "$TABLE" ] || { echo "no donor table: $TABLE" >&2; exit 1; }
[ -s "$HEADER" ] || { echo "no header: $HEADER" >&2; exit 1; }

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

cat "$HEADER" > "$TMP"

# AX001 is deliberately NOT emitted as a donor id. Its colonies are named BMH1_TG001_* and
# carry no PD id, so the scan's "$donor"* glob cannot find them — an AX001 line would scan
# nothing and look like a clean zero. They enter via `--samples ~/ax001.samples`. Its PD-named
# samples DO glob, under PD43976, which is emitted. AX001 and PD43976 are ONE person (see the
# header); counting both here would double-count the donor and scan the same person twice.
awk -F'\t' '
NR == 1 { next }
$1 !~ /^PD[0-9]+$/ { next }
!seen[$1]++ {
    donor[$1] = 1
    paper[$1] = $8
    # first row for a donor wins for the descriptive fields; they are per-donor, not
    # per-project, so any row carries them
    tips[$1] = $12; tissue[$1] = $3; unit[$1] = $4; age[$1] = $5; sex[$1] = $6; dx[$1] = $7
    order[++n] = $1
}
END {
    # group by paper, largest cohort first, so the file reads like the cohort list in the header
    for (d in donor) cohort[paper[d]]++
    ncoh = 0
    for (p in cohort) { size[++ncoh] = cohort[p]; name[ncoh] = p }
    for (i = 1; i <= ncoh; i++) for (j = i+1; j <= ncoh; j++)
        if (size[j] > size[i] || (size[j] == size[i] && name[j] < name[i])) {
            t = size[i]; size[i] = size[j]; size[j] = t
            t = name[i]; name[i] = name[j]; name[j] = t
        }

    total = 0
    for (i = 1; i <= ncoh; i++) {
        printf "\n# --- %s  (%d donors) ---\n", name[i], size[i]
        # donors within a cohort in id order
        ndon = 0
        for (k = 1; k <= n; k++) if (paper[order[k]] == name[i]) list[++ndon] = order[k]
        for (a = 1; a <= ndon; a++) for (b = a+1; b <= ndon; b++)
            if (list[b] < list[a]) { t = list[a]; list[a] = list[b]; list[b] = t }
        for (a = 1; a <= ndon; a++) {
            d = list[a]; total++
            note = tips[d] " tips; " tissue[d]
            if (unit[d] != "" && unit[d] != "-") note = note " (" unit[d] ")"
            if (age[d] != "" && age[d] != "-" && age[d] != "?") note = note "; age " age[d] " " sex[d]
            if (dx[d] != "" && dx[d] != "-") note = note "; " dx[d]
            if (length(note) > 150) note = substr(note, 1, 147) "..."
            printf "%-9s # %s\n", d, note
        }
        delete list
    }
    printf "\n# %d donors. Generated by cluster/trees/make_donors_txt.sh -- DO NOT EDIT BY HAND.\n", total
    printf "# Edit cluster/donors.header (prose) or cluster/trees/donor_table.tsv (the list), then re-run.\n"
}' "$TABLE" >> "$TMP"

if [ "${1:-}" = "--check" ]; then
    if cmp -s "$TMP" "$DEST"; then echo "donors.txt is up to date"; exit 0; fi
    echo "STALE: donors.txt differs from what donor_table.tsv generates" >&2
    diff -u "$DEST" "$TMP" | head -40 >&2
    exit 1
fi

mv -f "$TMP" "$DEST"
trap - EXIT
n=$(sed 's/#.*//' "$DEST" | awk 'NF' | wc -l | tr -d ' ')
echo "$DEST: $n donors"
