//! The part of annotate_v2.GeneModel (tools/annotate_v2.py:83-300) that the pre-mRNA lookup
//! (annotator._premrna_fn) uses: `_load`, `_resolve`, `_candidates`, `_genic_feature`,
//! `_splice_class` (windows from CONFIG['annotate'] splice_* / promoter_*; `_candidates` reaches
//! `promoter_up`, only the returned FEATURE KEYWORD is used by _premrna_fn).
//!
//! WP-TD. Tested against python by unit tests below (expected values generated by running
//! annotate_v2.GeneModel on the same track).

use crate::config::GeneModelCfg;
use std::io::BufRead;
use std::path::Path;

/// One gene: (start, end, name, strand, merged exons).
#[derive(Clone, Debug, PartialEq)]
pub struct Gene {
    pub start: i64,
    pub end: i64,
    pub name: String,
    pub strand: String,
    pub exons: Vec<(i64, i64)>,
}

/// annotate_v2.GeneModel (subset). Windows default like python.
pub struct GeneModel {
    pub donor_window: i64,
    pub acceptor_window: i64,
    pub ppt_window: i64,
    pub branch_window: i64,
    pub prom_up: i64,
    /// contig -> genes sorted by (start, end, name, ...) like python's tuple sort
    pub genes: rustc_hash::FxHashMap<String, Vec<Gene>>,
    pub maxspan: rustc_hash::FxHashMap<String, i64>,
}

fn pyint(s: &str) -> Result<i64, String> {
    s.trim().parse::<i64>().map_err(|_| format!("invalid literal for int(): '{s}'"))
}

impl GeneModel {
    /// `GeneModel(path, cfg)`: windows from `cfg`, genes from the per-exon track.
    pub fn open(path: &Path, cfg: &GeneModelCfg) -> Result<GeneModel, String> {
        let rd = crate::inputs::open_text(path).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
        // (contig, gene) -> (strand, intervals); first-seen strand wins (dict.setdefault)
        let mut order: Vec<(String, String)> = Vec::new();
        type Acc = rustc_hash::FxHashMap<(String, String), (String, Vec<(i64, i64)>)>;
        let mut acc: Acc = Default::default();
        for line in rd.lines() {
            let line = line.map_err(|e| format!("{}: {e}", path.display()))?;
            let line = line.trim_end_matches('\n');
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let f: Vec<&str> = line.split('\t').collect();
            if f.len() < 5 {
                continue;
            }
            let (start, end) = (pyint(f[1])?, pyint(f[2])?);
            let key = (f[0].to_string(), f[3].to_string());
            if !acc.contains_key(&key) {
                order.push(key.clone());
            }
            acc.entry(key).or_insert_with(|| (f[4].to_string(), Vec::new())).1.push((start, end));
        }
        let mut genes: rustc_hash::FxHashMap<String, Vec<Gene>> = Default::default();
        for key in order {
            let (strand, mut ivs) = acc.remove(&key).unwrap();
            ivs.sort();
            let mut merged: Vec<(i64, i64)> = vec![ivs[0]];
            for &(s, e) in &ivs[1..] {
                let l = merged.last_mut().unwrap();
                if s <= l.1 {
                    l.1 = l.1.max(e);
                } else {
                    merged.push((s, e));
                }
            }
            let (gs, ge) = (merged[0].0, merged.last().unwrap().1);
            genes.entry(key.0).or_default().push(Gene { start: gs, end: ge, name: key.1, strand, exons: merged });
        }
        let mut maxspan = rustc_hash::FxHashMap::default();
        for (contig, v) in genes.iter_mut() {
            v.sort_by(|a, b| (a.start, a.end, &a.name, &a.strand, &a.exons).cmp(&(b.start, b.end, &b.name, &b.strand, &b.exons)));
            maxspan.insert(contig.clone(), v.iter().map(|g| g.end - g.start).max().unwrap());
        }
        Ok(GeneModel {
            donor_window: cfg.splice_donor_window,
            acceptor_window: cfg.splice_acceptor_window,
            ppt_window: cfg.splice_ppt_window,
            branch_window: cfg.splice_branch_window,
            prom_up: cfg.promoter_up,
            genes,
            maxspan,
        })
    }

    /// `_resolve(contig)`: exact, else the chr-prefix alternative; None when absent.
    pub fn resolve(&self, contig: &str) -> Option<String> {
        if self.genes.contains_key(contig) {
            return Some(contig.to_string());
        }
        let alt = match contig.strip_prefix("chr") {
            Some(x) => x.to_string(),
            None => format!("chr{contig}"),
        };
        self.genes.contains_key(&alt).then_some(alt)
    }

    /// `_candidates(contig, p)`: genes whose body comes within prom_up of p, in python's order
    /// (right to left from the last gene starting <= p + prom_up). None when the contig is absent.
    pub fn candidates(&self, contig: &str, p: i64) -> Option<Vec<&Gene>> {
        let key = self.resolve(contig)?;
        let genes = &self.genes[&key];
        let reach = self.prom_up;
        let hi = p + reach;
        let lo_i = genes.partition_point(|g| g.start <= hi);
        let floor = p - reach - self.maxspan.get(&key).copied().unwrap_or(0);
        let mut out = Vec::new();
        for g in genes[..lo_i].iter().rev() {
            if g.start < floor {
                break;
            }
            if g.end + reach >= p {
                out.push(g);
            }
        }
        Some(out)
    }

    /// `_splice_class(dd, da)`: (rank, keyword, label) of an intronic point from its distance to
    /// the donor (dd) and acceptor (da) boundaries; the tightest match wins.
    pub fn splice_class(&self, dd: i64, da: i64) -> (i64, &'static str, &'static str) {
        if dd <= self.donor_window && dd <= da {
            return (1, "splice_donor", "splice donor");
        }
        if da <= self.acceptor_window {
            return (2, "splice_acceptor", "splice acceptor");
        }
        if da <= self.ppt_window {
            return (3, "polypyrimidine_tract", "polypyrimidine tract");
        }
        if da <= self.branch_window {
            return (4, "branch_point", "branch point (lariat)");
        }
        if dd <= self.donor_window {
            return (1, "splice_donor", "splice donor");
        }
        (5, "intron", "intron")
    }

    /// `_genic_feature(exons, strand, p)` -> (rank, keyword, label) for p inside a gene body.
    pub fn genic_feature(&self, exons: &[(i64, i64)], strand: &str, p: i64) -> (i64, &'static str, &'static str) {
        for &(s, e) in exons {
            if s <= p && p < e {
                return (0, "exon", "exonic");
            }
        }
        for w in exons.windows(2) {
            let le = w[0].1; // first intron base
            let rs = w[1].0; // last intron base is rs-1
            if le <= p && p < rs {
                let d_left = p - le + 1;
                let d_right = rs - p;
                let (dd, da) = if strand == "+" { (d_left, d_right) } else { (d_right, d_left) };
                return self.splice_class(dd, da);
            }
        }
        (5, "intron", "intron")
    }
}
