#!/bin/bash
# =============================================================================
# cluster/hsc_run.sh — the deployed TPRT pipeline, one patient at a time (farm22).
#
# The configuration validated on PD37590 (arm C + genotype2 with reference-bias correction),
# from ONE checkout of branch hsc-deploy:
#   discovery   config.discovery.grch38.tprt2frag  (>= 2 fragments per junction end IN EACH colony)
#   combine     Rust peartree-combine, src/config.py = config.py.grch38.tprt (+ tprt/arm_config.py)
#   genotype    peartree-genotype2, config.genotype2.grch38.refbias, two-sided loci only
#   joint       --ref-bias auto (global / per kind / per colony), colony zygosity, no NOISE cap
#   annotate    annotate_v2 + RTE library (tools/rte), locus_class
#   report      tools/phylo/tree_fit.py + cluster/somatic_table.py -> <P>.somatic.xlsx
#
# Usage (head node, from anywhere):
#   bash <checkout>/cluster/hsc_run.sh setup              # build binaries, venv link, src/config.py
#   bash <checkout>/cluster/hsc_run.sh populate <P>       # bsub: fill patients/*/<P>/colonies.tsv
#   bash <checkout>/cluster/hsc_run.sh submit <P>         # samples.tsv + the whole pipeline
#   bash <checkout>/cluster/hsc_run.sh status <P>
#
# Layout:  $HSC_ROOT/<P>/<P>/      pipeline run dir (discovery/ insertions/ genotypes/ fit/ logs/ ...)
#          $HSC_ROOT/tmp/<P>/      annotate scratch
#          $HOME/results/hsc/<P>/  NFS copies: calls, joint table, annotation, <P>.somatic.xlsx
# Env overrides: HSC_ROOT, VENV, KEEP_BAMS=1 (skip the staged-BAM cleanup), plus every
# pipeline.sh knob (GT_THROTTLE, CI_MEM, ...).
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PT_ROOT="$(cd "$HERE/.." && pwd)"
JD="${JD:-/lustre/scratch126/casm/teams/team273/users/jd43}"
TPRT_ROOT="${TPRT_ROOT:-$JD/tprt_ab}"                 # shared resources (hs1.2bit, gene model, minimap2)
TPRT_RES="${TPRT_RES:-$TPRT_ROOT/resources}"
HSC_ROOT="${HSC_ROOT:-$JD/hsc}"
VENV="${VENV:-$TPRT_ROOT/PEAR-TREE/venv}"            # the tprt kit venv (edlib, mappy, pandas, scipy)
RESULTS_ROOT="${RESULTS_ROOT:-$HOME/results/hsc}"
RUST_MODULE="${RUST_MODULE:-rust/1.87.0}"

die()  { echo "hsc_run: $*" >&2; exit 1; }
note() { echo "[$(date +%H:%M:%S)] $*" >&2; }

patient_dir() {
    local d; d=$(ls -d "$PT_ROOT"/patients/*/"$1" 2>/dev/null || true)
    [ "$(printf '%s\n' "$d" | grep -c .)" -eq 1 ] || die "expected exactly one patients/*/$1 in $PT_ROOT, found: ${d:-none}"
    echo "$d"
}

cmd_setup() {
    [ -x "$VENV/bin/python" ] || die "no venv at $VENV (set VENV)"
    [ -e "$PT_ROOT/venv" ] || ln -s "$VENV" "$PT_ROOT/venv"   # install.sh check-config defaults to $PT_ROOT/venv
    note "building Rust binaries in $PT_ROOT"
    module load "$RUST_MODULE" >/dev/null 2>&1 || true
    bash "$PT_ROOT/cluster/build.sh"
    for b in peartree-discovery peartree-combine peartree-genotype2; do
        [ -x "$PT_ROOT/rust/$b/target/release/$b" ] || die "build did not produce $b"
    done
    cat > "$PT_ROOT/src/config.py" <<EOF
# GENERATED by cluster/hsc_run.sh setup — the TPRT configuration (arm B/C python side:
# cluster/config.py.grch38.tprt + cluster/tprt/arm_config.py). Do not edit.
import os
import sys
os.environ.setdefault('TPRT_ROOT', '$TPRT_ROOT')
os.environ.setdefault('TPRT_RES', '$TPRT_RES')
sys.path.insert(0, '$PT_ROOT/cluster/tprt')
from arm_config import build  # noqa: E402
TPRT_AB_ARM = 'B'
CONFIG = build(TPRT_AB_ARM)
EOF
    (cd "$PT_ROOT" && "$VENV/bin/python" -c "import sys; sys.path.insert(0, 'src'); import config; \
sys.path.insert(0, 'cluster/tprt'); import arm_config; print(arm_config.describe(config.TPRT_AB_ARM))")
    note "setup done at $(git -C "$PT_ROOT" log --oneline -1)"
}

cmd_populate() {
    local P="${1:?usage: hsc_run.sh populate <PATIENT_ID>}" d org
    d="$(patient_dir "$P")"; org="$(basename "$(dirname "$d")")"
    mkdir -p "$PT_ROOT/logs"
    cd "$PT_ROOT"
    ONLY="$org" bsub -K < cluster/populate_colonies_tsv.sh
    grep -v '^#' "$d/colonies.tsv" | awk -F'\t' 'NR>1 {n++; a[$6]++} END {printf "%d BAMs:", n; for (k in a) printf " %s=%d", k, a[k]; print ""}'
}

cmd_submit() {
    local P="${1:?usage: hsc_run.sh submit <PATIENT_ID>}" d
    d="$(patient_dir "$P")"
    ls "$d"/*.tree >/dev/null 2>&1 || die "no tree in $d"
    grep -v '^#' "$d/colonies.tsv" | awk 'NR>1' | grep -q . \
        || die "$d/colonies.tsv has no rows — run: bash $PT_ROOT/cluster/hsc_run.sh populate $P"
    [ -s "$PT_ROOT/src/config.py" ] && grep -q TPRT_AB_ARM "$PT_ROOT/src/config.py" \
        || die "no generated src/config.py — run: bash $PT_ROOT/cluster/hsc_run.sh setup"
    for b in peartree-discovery peartree-combine peartree-genotype2; do
        [ -x "$PT_ROOT/rust/$b/target/release/$b" ] || die "missing $b — run setup"
    done

    local W="$HSC_ROOT/$P"
    mkdir -p "$W" "$HSC_ROOT/tmp/$P"
    PATIENTS_DIR="$PT_ROOT/patients" bash "$PT_ROOT/cluster/fleet.sh" samples "$P" > "$W/samples.tsv"
    local n; n=$(grep -c . "$W/samples.tsv" || true)
    [ "$n" -gt 0 ] || die "fleet.sh samples $P listed no GRCh38 WGS colonies"
    note "$P: $n GRCh38 WGS samples -> $W/samples.tsv"

    env WORKROOT="$W" RESULTS_DIR="$RESULTS_ROOT" VENV="$VENV" \
        DISC_CFG="$PT_ROOT/cluster/config.discovery.grch38.tprt2frag" \
        GENO_CFG="$PT_ROOT/cluster/config.genotype.grch38.tprt" GENO_ONE_SIDED=0 \
        GENOTYPE_IMPL=v2 GENO2_CFG="$PT_ROOT/cluster/config.genotype2.grch38.refbias" \
        JOINT_ARGS="--ref-bias auto" COMBINE_IMPL=rust \
        TPRT_ANNOT_TMP="$HSC_ROOT/tmp/$P" \
        GT_THROTTLE="${GT_THROTTLE:-20}" GT_MEM_T1="${GT_MEM_T1:-4000}" GT_MEM_T2="${GT_MEM_T2:-16000}" \
        SD_MEM_T1="${SD_MEM_T1:-4000}" CI_MEM="${CI_MEM:-16000}" CI_CORES="${CI_CORES:-8}" \
        AN_MEM="${AN_MEM:-32000}" AN_CORES="${AN_CORES:-4}" \
        PT_JOB_PREFIX="${P}_hsc" PT_NO_CLEANUP="${KEEP_BAMS:-0}" PT_JOBIDS_FILE="$W/jobids.tsv" \
        bash "$PT_ROOT/cluster/pipeline.sh" submit-list "$P" "$W/samples.tsv"
    note "results will land in $RESULTS_ROOT/$P (final: $P.somatic.xlsx)"
}

cmd_status() {
    local P="${1:?usage: hsc_run.sh status <PATIENT_ID>}"
    PT_JOB_PREFIX="${P}_hsc" WORKROOT="$HSC_ROOT/$P" bash "$PT_ROOT/cluster/pipeline.sh" status "$P"
}

case "${1:-}" in
    setup)    shift; cmd_setup "$@" ;;
    populate) shift; cmd_populate "$@" ;;
    submit)   shift; cmd_submit "$@" ;;
    status)   shift; cmd_status "$@" ;;
    *) sed -n '2,27p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
