#!/usr/bin/env python3
"""Write a combine config for the equivalence harness (tests/equiv.sh).

`<out>/config.py` = a cluster config (`--base`, e.g. cluster/config.py.grch38.tprt) exec'd
verbatim, with the farm paths replaced by the fixture resources and optional
`--override KEY=PYTHON_LITERAL` applied to CONFIG['combine_insertions'] last. Both the python
reference (test/e2e/run_combine.py --config-dir <out>) and the Rust binary
(--config <out>/config.py) read this same file. A JSON dump (`config.json`, lambdas -> null) is
written next to it for Rust runs without python.
"""
import argparse
import json
import os
import runpy
import shutil


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", required=True, help="cluster/config.py.* to start from")
    ap.add_argument("--out", required=True, help="output directory (config.py, config.json)")
    ap.add_argument("--genome-2bit", required=True)
    ap.add_argument("--bt2-index", required=True)
    ap.add_argument("--chain", required=True)
    ap.add_argument("--override", action="append", default=[])
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    txt = f'''# generated by rust/peartree-combine/tests/make_config.py -- do not edit
_BASE = {os.path.abspath(a.base)!r}
exec(compile(open(_BASE).read(), _BASE, "exec"))
CI = CONFIG["combine_insertions"]
CI.update({{
    "genome_2bit": {os.path.abspath(a.genome_2bit)!r},
    "samtools_executable": {shutil.which("samtools")!r},
    "bowtie2_executable": {shutil.which("bowtie2")!r},
    "bowtie2_index": {os.path.abspath(a.bt2_index)!r},
    "bowtie2_index2": {os.path.abspath(a.bt2_index)!r},
    "bowtie2_index2_lo": {os.path.abspath(a.chain)!r},
}})
'''
    for ov in a.override:
        k, v = ov.split("=", 1)
        txt += f"CI[{k!r}] = {v}\n"
    path = os.path.join(a.out, "config.py")
    with open(path, "w") as fh:
        fh.write(txt)
    cfg = runpy.run_path(path)["CONFIG"]
    with open(os.path.join(a.out, "config.json"), "w") as fh:
        json.dump(cfg, fh, default=lambda o: None, indent=1, sort_keys=True)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
