#!/usr/bin/env python3
"""E2E helper: write a local `config.py` = cluster/config.py.grch38.tprt with the farm paths
replaced by the E2E resources (reduced reference bowtie2 index, identity chain, hg38 2bit,
converted rmsk, local family HMM, nhmmscan back-end). The .tprt combine/annotate keys
(independent-fragment gate, lenient dedup, indel-aware consensus, SHORT overhang reads,
rte_library) are inherited unchanged."""
import argparse
import os
import shutil


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--ref-dir", required=True)
    ap.add_argument("--hg38-2bit", required=True)
    ap.add_argument("--hs1-2bit", required=True)
    ap.add_argument("--workdir", required=True)
    a = ap.parse_args()
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    tprt = os.path.join(a.repo, "cluster", "config.py.grch38.tprt")
    ref = os.path.join(a.ref_dir, "reduced")
    txt = f'''# generated by test/e2e/make_config.py -- do not edit
_TPRT = {tprt!r}
exec(compile(open(_TPRT).read(), _TPRT, "exec"))
CI = CONFIG["combine_insertions"]
CI.update({{
    "genome_2bit": {a.hg38_2bit!r},
    "samtools_executable": {shutil.which("samtools")!r},
    "bowtie2_executable": {shutil.which("bowtie2")!r},
    "bowtie2_index": {ref!r},
    "bowtie2_index2": {ref!r},
    "bowtie2_index2_lo": {os.path.join(a.ref_dir, "identity.chain.gz")!r},
}})
A = CONFIG["annotate"]
A.update({{
    "rmsk": {os.path.join(a.ref_dir, "reduced.rmsk.out.gz")!r},
    "exon_annotation": None,
    "hmm": {os.path.join(a.repo, "test", "fullstack", "annotate", "peartree_rte.hmm")!r},
    "dfamscan": None,
    "hmmer": None,
    "tmp": lambda ext: (lambda s: f"{a.workdir}/{{s}}.{{ext}}"),
    "rte_library": "resources/rte_library",      # relative on purpose: resolved by tools/rte
    "genome_2bit": {a.hg38_2bit!r},
    "remap_2bit": {a.hs1_2bit!r},
    "remap_rmsk": None,
}})
'''
    with open(a.out, "w") as fh:
        fh.write(txt)
    print(f"wrote {a.out}")


if __name__ == "__main__":
    main()
