"""src/config.py builder for the TPRT A/B arms (cluster/tprt/setup.sh writes the stub).

Each worktree's src/config.py is a 4-line stub generated by `setup.sh configs`:

    import sys; sys.path.insert(0, '<that worktree>/cluster/tprt')
    from arm_config import build
    TPRT_AB_ARM = 'A'            # or 'B'
    CONFIG = build(TPRT_AB_ARM)

so the canonical configs stay the single source of truth and the A/B differences are the
explicit, short list below rather than two hand-edited copies that drift apart.

  arm A  base = cluster/config.py.grch38        (current pipeline: every TPRT combine key off)
  arm B  base = cluster/config.py.grch38.tprt   (TPRT-hallmark combine keys on)

Overrides applied to BOTH arms (annotation is the measuring instrument of the comparison, not
part of the pipeline under test, so both arms are annotated with the same instrument; it never
changes which loci are called):
  * annotate.tmp          per-arm scratch dir. The base configs share
                          /lustre/.../jd43/tmp/{patient}.{ext}; both arms annotate the same
                          patient concurrently and would overwrite each other's dfam/sam files.
  * annotate.rte_library / genome_2bit / remap_rmsk   the .tprt annotate block (arm A's base has
                          none, so it would get no tprt_score / element / structure columns).
  * annotate.exon_annotation   the hs1 RefSeq gene model (tools/build_gene_model.py --curated);
                          both bases ship None (pseudogenes then cannot be proven).
  * annotate.remap_2bit   hs1.2bit (exon-junction cores, novel-source identity).
  * annotate.remap_index  hs1 minimap2 index, ONLY if present (novel-source locator; optional).
  * annotate.hmmer        the HMMER bin dir chosen by `setup.sh hmmer` ($TPRT_RES/hmmer_bin), if
                          that file exists; the bases' $JD/hmmer-3.3.2/bin no longer exists.
  * combine_genotypes.min_wild-types = 1   the bases' 20 is "of 90 pooled colonies"; one patient
                          has ~10, so NO locus could pass (PD37449: 5189/5189 removed). >= 1
                          wild-type colony still removes all-colony (germline-like) loci; the
                          dispersion gate is unchanged.
  * combine_genotypes.write_unfiltered + annotate.genotyping_file   annotate scores EVERY locus
                          with >= 1 carrier (<P>.genotypes.unfiltered.csv.gz), not only the
                          gate survivors: the A/B measures how well the TPRT score and the gates
                          separate tree-consistent from tree-violating calls, which needs both
                          sides annotated. tree_fit still flags gate survivors from
                          <P>.genotypes.csv.gz.

Resource directory: env TPRT_RES (default /lustre/.../jd43/tprt_ab/resources), tmp root: env
TPRT_ROOT. Missing files are NOT silently dropped here (except the optional remap_index): the
preflight (cluster/tprt/preflight.sh) checks every path this module produces.
"""
import importlib.machinery
import importlib.util
import os

_HERE = os.path.dirname(os.path.realpath(__file__))     # <worktree>/cluster/tprt
_ROOT = os.path.dirname(os.path.dirname(_HERE))         # <worktree>
_JD = os.environ.get('JD', '/lustre/scratch126/casm/teams/team273/users/jd43')
TPRT_ROOT = os.environ.get('TPRT_ROOT', os.path.join(_JD, 'tprt_ab'))
TPRT_RES = os.environ.get('TPRT_RES', os.path.join(TPRT_ROOT, 'resources'))

BASES = {'A': 'cluster/config.py.grch38', 'B': 'cluster/config.py.grch38.tprt'}
ANNOTATE_FROM_TPRT = ('rte_library', 'genome_2bit', 'remap_rmsk')

RESOURCES = {
    'exon_annotation': os.path.join(TPRT_RES, 'hs1.gene_model.tsv.gz'),
    'remap_2bit': os.path.join(TPRT_RES, 'hs1.2bit'),
    'remap_index': os.path.join(TPRT_RES, 'hs1.sr.mmi'),          # optional
}


def _load(relpath, name):
    path = os.path.join(_ROOT, relpath)
    loader = importlib.machinery.SourceFileLoader(name, path)    # base files have no .py suffix
    spec = importlib.util.spec_from_loader(name, loader)
    mod = importlib.util.module_from_spec(spec)
    loader.exec_module(mod)
    return mod.CONFIG


def tmp_dir(arm):
    return os.path.join(TPRT_ROOT, 'tmp', arm)


def build(arm):
    if arm not in BASES:
        raise ValueError(f"arm must be A or B, got {arm!r}")
    cfg = _load(BASES[arm], f'_pt_base_config_{arm}')
    ann = cfg['annotate']
    if arm == 'A':
        tprt_ann = _load(BASES['B'], '_pt_base_config_B_annotate')['annotate']
        for k in ANNOTATE_FROM_TPRT:
            ann[k] = tprt_ann[k]
    tdir = tmp_dir(arm)
    ann['tmp'] = lambda extension: lambda sample: os.path.join(tdir, f'{sample}.{extension}')
    ann['exon_annotation'] = RESOURCES['exon_annotation']
    ann['remap_2bit'] = RESOURCES['remap_2bit']
    if os.path.exists(RESOURCES['remap_index']):
        ann['remap_index'] = RESOURCES['remap_index']
    # HMMER bin dir resolved by `setup.sh hmmer` (the bases' $JD/hmmer-3.3.2/bin is gone)
    cg = cfg['combine_genotypes']
    cg['min_wild-types'] = 1
    cg['write_unfiltered'] = True
    ann['genotyping_file'] = lambda sample: f'{sample}.genotypes.unfiltered.csv.gz'
    hb = os.path.join(TPRT_RES, 'hmmer_bin')
    if os.path.exists(hb):
        with open(hb) as f:
            d = f.read().strip()
        if d:
            ann['hmmer'] = d
    return cfg


def describe(arm):
    """Human-readable summary for preflight / setup (python3 arm_config.py A)."""
    cfg = build(arm)
    ci, ann = cfg['combine_insertions'], cfg['annotate']
    keys = ['require_independent_fragments', 'indel_aware_consensus', 'count_short_overhang',
            'merge_tolerance_bp', 'slippage_reject', 'far_pair_strict']
    out = [f"arm {arm}: base {BASES[arm]}",
           f"  combine genome_2bit={ci['genome_2bit']}",
           f"  combine chain={ci['bowtie2_index2_lo']}",
           "  combine TPRT keys: " + ', '.join(f"{k}={ci.get(k, '(unset)')}" for k in keys),
           f"  annotate tmp={tmp_dir(arm)}",
           f"  annotate rte_library={ann.get('rte_library')} exon_annotation={ann.get('exon_annotation')}",
           f"  annotate remap_2bit={ann.get('remap_2bit')} remap_index={ann.get('remap_index', '(absent: novel-source locator off)')}"]
    return '\n'.join(out)


if __name__ == '__main__':
    import sys
    for a in (sys.argv[1:] or ['A', 'B']):
        print(describe(a))
